### ISSUE TITLE
Calculating allocations from GCHeapStats events

### ISSUE THREAD

**Issue by giulianob** [Maoni0/mem-doc#16]
Is it possible to figure out total allocations purely from looking at [GCHeapStats](https://docs.microsoft.com/en-us/dotnet/framework/performance/garbage-collection-etw-events#gcheapstats_v1-event)? I would like to be able to use GCHeapStats to know how much memory was allocated during a certain time period.

I am using `TraceEventSession` to get the data. In particular, I was not expecting to see multiple records with Gen0 unchanged. I was under the impression GCHeapStats happened after each collection therefore I expected Gen0 to always be collected and change.

| FinalizationPromotedBytes | FinalizationPromotedCount | Generation | Generation0Bytes | Generation1Bytes | Generation2Bytes | Generation3Bytes | Generation4Bytes | PinnedObjectCount | SinkBlockCount | TotalHeapSizeBytes | TotalPromoted0Bytes | TotalPromoted1Bytes | TotalPromoted2Bytes | TotalPromoted3Bytes | TotalPromoted4Bytes | TotalPromotedBytes |
|------------------------------------|------------------------------------|---------------------|---------------------------|---------------------------|---------------------------|---------------------------|---------------------------|----------------------------|-------------------------|-----------------------------|------------------------------|------------------------------|------------------------------|------------------------------|------------------------------|-----------------------------|
| 3360                               | 21                                 | 2                   | 78729160                  | 3482248                   | 21868696                  | 15269320                  | 0                         | 0                          | 60                      | 119349424                   | 3359000                      | 359864                       | 18712624                     | 4817288                      | 0                            | 27248776                    |
| 3360                               | 35                                 | 2                   | 78729160                  | 3482248                   | 21868696                  | 15038408                  | 0                         | 0                          | 60                      | 119118512                   | 3359000                      | 359864                       | 18712624                     | 5667896                      | 0                            | 28099384                    |
| 36636                              | 45                                 | 2                   | 47662456                  | 4855672                   | 24150720                  | 13164024                  | 0                         | 0                          | 57                      | 89832872                    | 4837904                      | 944528                       | 22425736                     | 5954736                      | 0                            | 34162904                    |

**Comment by Maoni0** [comment]
hi @giulianob there's no way to get allocated just from that one event as it only captures info *after* a GC. in order to get it we need info before the GC too. is it possible for you to use the TraceEvent library that already [exposes](https://github.com/microsoft/perfview/blob/main/src/TraceEvent/Computers/TraceManagedProcess.cs#L2461) this info? 

```csharp
public double[] UserAllocated = new double[(int)Gens.MaxGenCount];
```
this is [how PerfView gets it](https://github.com/microsoft/perfview/blob/330c6a8569579c1db20c03235a1155087f310a33/src/PerfView/GcStats.cs#L721).

**Comment by giulianob** [comment]
Thanks that looks like a lot of good info. I'll look into it.
