### ISSUE TITLE
Is there any plan to improve the translation quality of the Chinese version?

### ISSUE THREAD

**Issue by xiaofeng-zheng** [Maoni0/mem-doc#26]
I noticed that some translations were not very accurate or idiomatic. Is there any plan to improve the translation quality of the Chinese version? Or would you mind if someone else submits PRs to help?

**Comment by InCerryGit** [comment]
> I noticed that some translations were not very accurate or idiomatic. Is there any plan to improve the translation quality of the Chinese version? Or would you mind if someone else submits PRs to help?

Of course you can. because of the length of the article and the fact that I have little spare time, I relied on machine translation for most of it and only did a few proofreads. If you can submit a higher quality translation, that would be great.

**Comment by Maoni0** [comment]
I concur with what @InCerryGit said. 

if you would like to contribute, of course it would be very much appreciated!

**Comment by xiaofeng-zheng** [comment]
Thanks for your replies. Will try to contribute when I have some spare time 🙂
