### ISSUE TITLE
One line not show after markdown be rendered

### ISSUE THREAD

**Issue by personball** [Maoni0/mem-doc#35]
I found this line not show when the markdown text rendered. Maybe by, I guess the Xml Tag not closed.

https://github.com/Maoni0/mem-doc/blob/f2dee5ee0bc54ffeef2b3eeace336aa0bb2892a9/doc/.NETMemoryPerformanceAnalysis.md?plain=1#L944

Should we mark these lines as code block like:

```xml
<GCEvent GCNumber="9" GCGeneration="0" Reason="AllocSmall">
<GlobalHeapHistory **FinalYoungestDesired="9,830,400"** NumHeaps="12"/> 
```

But `FinalYoungestDesired="9,830,400"` in the code block not bold.

**Comment by Maoni0** [comment]
I think your code block idea is better. `FinalYoungestDesired="9,830,400"` wouldn't be bold but since it's already mentioned in the explanation it should be ok. would you like to submit a PR to fix this? 🙂

**Comment by Maoni0** [comment]
cool, thank you!
